<?php

use Illuminate\Database\Seeder;

class MarcasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        \App\Marca::insert([
            [
                'marca'=>'Abarth'
            ],
            [
                'marca'=>'Alfa Romeo'
            ],
            [
                'marca'=>'Aston Martin'
            ],
            [
                'marca'=>'Audi'
            ],
            [
                'marca'=>'Bentley'
            ],
            [
                'marca'=>'BMW'
            ],
            [
                'marca'=>'Cadillac'
            ],
            [
                'marca'=>'Caterham'
            ],
            [
                'marca'=>'Chevrolet'
            ],
            [
                'marca'=>'Citroen'
            ],
            [
                'marca'=>'Dacia'
            ],
            [
                'marca'=>'Ferrari'
            ],
            [
                'marca'=>'Fiat'
            ],
            [
                'marca'=>'Ford'
            ],
            [
                'marca'=>'Honda'
            ],
            [
                'marca'=>'Infiniti'
            ],
            [
                'marca'=>'Isuzu'
            ],
            [
                'marca'=>'Iveco'
            ],
            [
                'marca'=>'Jaguar'
            ],
            [
                'marca'=>'Jeep'
            ],
            [
                'marca'=>'Kia'
            ],
            [
                'marca'=>'KTM'
            ],
            [
                'marca'=>'Lada'
            ],
            [
                'marca'=>'Lamborghini'
            ],
            [
                'marca'=>'Lancia'
            ],
            [
                'marca'=>'Land Rover'
            ],
            [
                'marca'=>'Lexus'
            ],
            [
                'marca'=>'Lotus'
            ],
            [
                'marca'=>'Maserati'
            ],
            [
                'marca'=>'Mazda'
            ],
            [
                'marca'=>'Mercedes-Benz'
            ],
            [
                'marca'=>'Mini'
            ],
            [
                'marca'=>'Mitsubishi'
            ],
            [
                'marca'=>'Morgan'
            ],
            [
                'marca'=>'Nissan'
            ],
            [
                'marca'=>'Opel'
            ],
            [
                'marca'=>'Peugeot'
            ],
            [
                'marca'=>'Piaggio'
            ],
            [
                'marca'=>'Porsche'
            ],
            [
                'marca'=>'Renault'
            ],
            [
                'marca'=>'Rolls-Royce'
            ],
            [
                'marca'=>'Seat'
            ],
            [
                'marca'=>'Skoda'
            ],
            [
                'marca'=>'Smart'
            ],
            [
                'marca'=>'SsangYong'
            ],
            [
                'marca'=>'Subaru'
            ],
            [
                'marca'=>'Tata'
            ],
            [
                'marca'=>'Suzuki'
            ],
            [
                'marca'=>'Tesla'
            ],
            [
                'marca'=>'Toyota'
            ],
            [
                'marca'=>'Volkswagen'
            ],
            [
                'marca'=>'Volvo'
            ]
        ]);
    }
}
